### ISSUE TITLE
Any logs?

### ISSUE THREAD

**Issue by rakshazi** [Divested-Mobile/hypatia#1]
Hello,
I tried to use Hypatia, but it has no real-time logs while scanning. I see message `Starting scan.... NNN files pedning scan` and nothing more.

Could you add (optional) verbose log output to check any progress, please?

**Comment by SkewedZeppelin** [comment]
> nothing more

After the pending message the scan is hashing the files.
However because some of it is on the main thread it causes hangs, and the start scan button can also stop a scan.
Maybe you hit the button twice (/or it hung and thought it was pressed twice)?

There was a rewrite I started back in 2018, never really got around to finishing.
imo malware scanners aren't the most useful, and I have instead been focusing on hardening the OS.

I will try to add some extra messages in free time.
Thank you for reaching out.
