### ISSUE TITLE
Latest update changelog/database selection removed? 

### ISSUE THREAD

**Issue by Ricat87** [Divested-Mobile/hypatia#52]
Hypatia just updated to 2.35. I haven't launched the app in quite a while.

I can't select the databases anymore, they all seem to be named variations of hypatia-bloom, and upon scanning the number of signatures is shown as "?"

I can't find a changelog on F-Droid, the Divest site, or on this Github.

What's going on? This makes me feel uneasy.

**Comment by SkewedZeppelin** [comment]
https://infosec.exchange/@divested/111622679578953768

I'll add a news entry to divestos.org soon.

The ? is there because I can't actually count the number of entries in the bloom format due to how they work, and rewording it would require new translations.

tl;dr new database format allows using all 4.9million signatures by default very efficiently

**Comment by SkewedZeppelin** [comment]
I've added a note to the website: https://divestos.org/pages/news

It was also talked about in the chat: https://divestos.org/pages/community
The idea to do this was even from another user there :)

**Comment by SkewedZeppelin** [comment]
There is now a count available here: https://divested.dev/MalwareScannerSignatures/

**Comment by Ricat87** [comment]
Thanks!! I have never followed the chat or Twitter or anything. I just installed Hypatia from F-Droid ._____.
