### ISSUE TITLE
False Positive Detection of Hypatia’s Own Test Files

### ISSUE THREAD

**Issue by Xtreme-X7** [Divested-Mobile/hypatia#92]
False Positive Detection of Hypatia’s Own Test Files

I wanted to bring to your attention an issue I've encountered while using Hypatia on my Android device. During recent scans, the app has been flagging its own test files—specifically the MD5, SHA-1, and SHA-256 test files it generates before every scan—as potential threats.

I understand that these files are likely produced as part of the app's internal checks to ensure that the hashing functions are working correctly. However, it's causing confusion when these test files are then flagged as malware during the scan.

Could you please look into this issue? It would be great if these test files could be excluded from detection to avoid any unnecessary alarms.

Thank you for your assistance, and for the ongoing development of Hypatia.

 i got it generated by Chat GPT because uh my English isn't that good

**Comment by SkewedZeppelin** [comment]
This is expected. There are two different self test mechanisms.

An internal one run every scan and a manual run one when the user taps the "Write self test files" button.

The internal one does not create files and will never generate an alert.

The manual one will write/save files and will generate alerts. But the user must manually delete those files after otherwise they will keep getting alerts.

**Comment by Xtreme-X7** [comment]
Ohh 😯 Yeah I noticed but didn't bother to include that in the issue thank you buddy

**Comment by Xtreme-X7** [comment]
Oh wait wait I don't know anything about this uh like how this thing works but 
Will you tell me what's the use of these test files generated in Manual run 
For testing purposes?

**Comment by SkewedZeppelin** [comment]
Just for testing to allow the user to see that it can work.
